### ISSUE TITLE
hide clouds button not working

### ISSUE THREAD

**Issue by Thefatsparrow** [What42Pizza/What42s-Shader-Base#1]
**Describe the bug**
hide clouds button in fog setting does not working

**To Reproduce**
click hide cloud button in cloud setting on shader

**Context**
![2023-12-27_18 50 58](https://github.com/What42Pizza/What42s-Shader-Base/assets/86117177/38d5be6a-3787-44cd-ba2d-5b9f0a220ece)

**Comment by Thefatsparrow** [comment]
clouds: org.antlr.v4.runtime.misc.ParseCancellationException: line 4234:1 missing ';' at 'glcolor' says that aswell for the error

**Comment by What42Pizza** [comment]
Thanks for posting this, let me look at it for a bit

**Comment by What42Pizza** [comment]
Alright, it should be working now and I've put out an update
