### ISSUE TITLE
nightvision potions have no effect while using shader

### ISSUE THREAD

**Issue by pesegolsson** [What42Pizza/What42s-Shader-Base#2]
**Describe the bug**
while shader is active in iris, nightvision potions have no effect on brightness.

**To Reproduce**
give yourself nightvision effect either via command or potion

**Context**
running the latest (non beta) version for 1.21.x of iris and latest shader of modrinth!

would have been nice if it would work as i often use nightvision instead of torches while caving/mining.

**Comment by What42Pizza** [comment]
Okay I think I've got this fixed now, thanks for pointing it out
